// Generated by gencpp from file mote_ros/State.msg
// DO NOT EDIT!


#ifndef MOTE_ROS_MESSAGE_STATE_H
#define MOTE_ROS_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mote_ros
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : x_position(0.0)
    , y_position(0.0)
    , velocity(0.0)
    , yaw(0.0)
    , yaw_rate(0.0)  {
    }
  State_(const ContainerAllocator& _alloc)
    : x_position(0.0)
    , y_position(0.0)
    , velocity(0.0)
    , yaw(0.0)
    , yaw_rate(0.0)  {
  (void)_alloc;
    }



   typedef double _x_position_type;
  _x_position_type x_position;

   typedef double _y_position_type;
  _y_position_type y_position;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;





  typedef boost::shared_ptr< ::mote_ros::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mote_ros::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::mote_ros::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::mote_ros::State > StatePtr;
typedef boost::shared_ptr< ::mote_ros::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mote_ros::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mote_ros::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mote_ros::State_<ContainerAllocator1> & lhs, const ::mote_ros::State_<ContainerAllocator2> & rhs)
{
  return lhs.x_position == rhs.x_position &&
    lhs.y_position == rhs.y_position &&
    lhs.velocity == rhs.velocity &&
    lhs.yaw == rhs.yaw &&
    lhs.yaw_rate == rhs.yaw_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mote_ros::State_<ContainerAllocator1> & lhs, const ::mote_ros::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mote_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mote_ros::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mote_ros::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mote_ros::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mote_ros::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mote_ros::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mote_ros::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mote_ros::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdfa267761e7acb2cdb6844c4c075ccd";
  }

  static const char* value(const ::mote_ros::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdfa267761e7acb2ULL;
  static const uint64_t static_value2 = 0xcdb6844c4c075ccdULL;
};

template<class ContainerAllocator>
struct DataType< ::mote_ros::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mote_ros/State";
  }

  static const char* value(const ::mote_ros::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mote_ros::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_position\n"
"float64 y_position\n"
"float64 velocity\n"
"float64 yaw\n"
"float64 yaw_rate\n"
;
  }

  static const char* value(const ::mote_ros::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mote_ros::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_position);
      stream.next(m.y_position);
      stream.next(m.velocity);
      stream.next(m.yaw);
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mote_ros::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mote_ros::State_<ContainerAllocator>& v)
  {
    s << indent << "x_position: ";
    Printer<double>::stream(s, indent + "  ", v.x_position);
    s << indent << "y_position: ";
    Printer<double>::stream(s, indent + "  ", v.y_position);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTE_ROS_MESSAGE_STATE_H
