# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mote_ros/Yaw.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Yaw(genpy.Message):
  _md5sum = "1b1bf6d09d1901c86cf97837e897882f"
  _type = "mote_ros/Yaw"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 yaw_rad
float64 yaw_rate
float64 yaw_x_position
float64 yaw_y_position"""
  __slots__ = ['yaw_rad','yaw_rate','yaw_x_position','yaw_y_position']
  _slot_types = ['float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       yaw_rad,yaw_rate,yaw_x_position,yaw_y_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Yaw, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.yaw_rad is None:
        self.yaw_rad = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.yaw_x_position is None:
        self.yaw_x_position = 0.
      if self.yaw_y_position is None:
        self.yaw_y_position = 0.
    else:
      self.yaw_rad = 0.
      self.yaw_rate = 0.
      self.yaw_x_position = 0.
      self.yaw_y_position = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.yaw_rad, _x.yaw_rate, _x.yaw_x_position, _x.yaw_y_position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.yaw_rad, _x.yaw_rate, _x.yaw_x_position, _x.yaw_y_position,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.yaw_rad, _x.yaw_rate, _x.yaw_x_position, _x.yaw_y_position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.yaw_rad, _x.yaw_rate, _x.yaw_x_position, _x.yaw_y_position,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
